### ISSUE TITLE
Описати обʼєкт транзакції аплікації

### ISSUE THREAD

**Issue by so2niko** [VeronikaSoldatova09/Project-levelup#4]

**Comment by VeronikaSoldatova09** [comment]
const transaction = {
    id: 1, // Унікальний ідентифікатор транзакції
    description: "Покупка продуктів", // Опис транзакції
    amount: -50.00, // Сума грошей (від'ємне число для витрат, додатнє - для доходів)
    date: "2023-10-16", // Дата транзакції
    category: "Їжа", // Категорія транзакції (наприклад, їжа, житло, розваги тощо)
    type: "expense" // Тип транзакції (expense - витрати, income - дохід)
};
